name: labastro
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - jupyter
  - matplotlib
  - pandas
  - astropy
  - astroquery
  - scipy
  - numpy
  - seaborn
  - missingno
  - sklearn
  - os
  - shutil
  - collections
  - json
  - bs4